import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'React Code Test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white dark:bg-gray-200`}>
        <section>
              <div className='mx-3 md:mx-auto max-w-7xl py-12 sm:px-6 lg:px-8'>
                  <div className='mx-auto max-w-4xl'>
                      {children}
                  </div>
              </div>
          </section>
      </body>
    </html>
  )
}
